"""
Django settings for avtolink project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['linkavto.ru', 'www.linkavto.ru', '127.0.0.1', '.linkavto.ru', '89.23.97.97',]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'shop',
    'orders',
    'cart',
    'checkout',
    'import_export',
    'simple_history',
    'django_celery_results',
    'accounts',
    'favorites',
    'search.apps.SearchConfig',
    'django.forms',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'search.middleware.SearchHistoryMiddleware',

]

ROOT_URLCONF = 'avtolink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.categories',
                'cart.context_processors.cart',
                'search.context_processors.search_history'

            ],
        },
    },
]

WSGI_APPLICATION = 'avtolink.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Общая статика
    os.path.join(BASE_DIR, 'shop/static'),  # Путь к статике приложения shop
    os.path.join(BASE_DIR, 'accounts/static'),  # Путь к статике приложения accounts
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Добавьте в конец файла:
LOGIN_URL = '/account/'  # URL для редиректа при необходимости авторизации
LOGIN_REDIRECT_URL = 'accounts:dashboard'  # Куда перенаправлять после входа
LOGOUT_REDIRECT_URL = 'index'  # Куда перенаправлять после выхода
CART_SESSION_ID = 'cart'  # Ключ для хранения корзины в сессии
CELERY_TASK_ALWAYS_EAGER = True
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'django-cache'
CELERY_CACHE_BACKEND = 'django-cache'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для тестирования
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Реальная отправка
# EMAIL_BACKEND = 'accounts.email_backend.RegRuEmailBackend'  # Кастомный backend для reg.ru
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
FAVORITES_CONFIG = {
    'MAX_ITEMS': 100,  # Лимит избранного
    'SESSION_SAVE': True,  # Сохранять для анонимов
}
# SMS настройки
SMSC_LOGIN = os.getenv('SMSC_LOGIN', '')
SMSC_PASSWORD = os.getenv('SMSC_PASSWORD', '')
SMSC_SENDER = 'LinkAvto'



# Настройки для реальной отправки email (reg.ru)
EMAIL_HOST = '31.31.196.47'  # IP адрес из DNS записей
EMAIL_PORT = 25  # Стандартный SMTP порт
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'linkavto@linkavto.ru'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')   # Пароль от почты
DEFAULT_FROM_EMAIL = 'linkavto@linkavto.ru'
SERVER_EMAIL = 'linkavto@linkavto.ru'


EMAIL_TIMEOUT = 30

# Дополнительные настройки SSL для reg.ru
import ssl
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
EMAIL_SSL_CERT_REQS = ssl.CERT_NONE  # Игнорируем проверку SSL сертификата

# Настройка для отключения проверки SSL в Django
import ssl
from django.core.mail.utils import DNS_NAME
ssl._create_default_https_context = ssl._create_unverified_context

# Настройки платежной системы
PAYMENT_SYSTEM = {
    'MERCHANT_ID': 'your_merchant_id',
    'SECRET_KEY': 'your_secret_key',
    'SBP_MERCHANT_ACCOUNT': 'your_sbp_account',
    'TEST_MODE': True,  # Режим тестирования
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

# Логирование транзакций
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'level': 'INFO',
            'handlers': ['console'],
        },
        'orders': {
            'level': 'INFO',
            'handlers': ['console'],
        },
        'django.server': {
            'level': 'INFO',
            'handlers': ['console'],
            'propagate': False,
        },
        # Добавьте логгер для почты
        'django.core.mail': {
            'level': 'DEBUG',
            'handlers': ['console', 'file'],
            'propagate': False,
        },
        'accounts': {
            'level': 'DEBUG',
            'handlers': ['console', 'file'],
            'propagate': False,
        },
        'accounts.views': {
            'level': 'DEBUG',
            'handlers': ['console', 'file'],
            'propagate': False,
        },
        'django.core.mail': {
            'level': 'DEBUG',
            'handlers': ['console', 'file'],
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

CACHE_TIMEOUT = {
    'home_page': 3600,  # 1 час
    'product_blocks': 1800,  # 30 минут
}
