# Generated by Django 5.1.5 on 2026-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_add_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shipping_address',
            field=models.TextField(blank=True, default='', help_text='Адрес склада/отправки товара — используется для расчёта стоимости доставки', verbose_name='Адрес отправки'),
        ),
    ]
