# Generated by Django 5.1.5 on 2026-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_add_seller_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='website_url',
            field=models.URLField(blank=True, default='', verbose_name='Адрес сайта магазина'),
        ),
    ]
