# Generated by Django 5.1.5 on 2026-01-04 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Количество результатов')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время запроса')),
                ('is_autocomplete', models.BooleanField(default=False, verbose_name='Автодополнение')),
                ('is_vin_search', models.BooleanField(default=False, verbose_name='Поиск по VIN')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры поиска')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_sear_user_id_2836be_idx'), models.Index(fields=['session_key', 'created_at'], name='search_sear_session_d2f83d_idx')],
            },
        ),
    ]
