# Generated by Django 6.0.3 on 2026-03-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_internal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='product',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_products', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Причина отклонения или запроса правок', verbose_name='Замечания модератора'),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('suspended', 'Приостановлен'), ('revision', 'Требует правок')], db_index=True, default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
