# Generated by Django 5.1.5 on 2026-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_product_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, help_text='Товар будет отображаться во всех выбранных категориях', related_name='extra_products', to='shop.category', verbose_name='Дополнительные категории'),
        ),
    ]
