# Generated by Django 5.1.5 on 2026-04-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_product_extra_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='product_brands/', verbose_name='Логотип')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд товара',
                'verbose_name_plural': 'Бренды товаров',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productbrand', verbose_name='Бренд товара'),
        ),
        migrations.CreateModel(
            name='ProductBrandCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='shop.productbrand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_relations', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Привязка бренда к категории',
                'verbose_name_plural': 'Привязки брендов к категориям',
                'unique_together': {('brand', 'category')},
            },
        ),
        migrations.AddField(
            model_name='productbrand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_brands', through='shop.ProductBrandCategoryRelation', to='shop.category', verbose_name='Категории'),
        ),
    ]
