# Generated by Django 5.1.5 on 2026-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марка легкового автомобиля', 'verbose_name_plural': 'Марки легковых автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='motobrand',
            options={'verbose_name': 'Марка мототехники', 'verbose_name_plural': 'Марки мототехники'},
        ),
        migrations.AlterModelOptions(
            name='specialbrand',
            options={'verbose_name': 'Марка спецтехники', 'verbose_name_plural': 'Марки спецтехники'},
        ),
        migrations.AlterModelOptions(
            name='truckbrand',
            options={'verbose_name': 'Марка грузовой техники', 'verbose_name_plural': 'Марки грузовой техники'},
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', help_text='Страна, в которой произведён товар', max_length=100, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='under_order',
            field=models.BooleanField(default=False, help_text='Товар доступен только под заказ', verbose_name='Под заказ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Высота в миллиметрах', max_digits=8, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Длина в миллиметрах', max_digits=8, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Ширина в миллиметрах', max_digits=8, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
