# Generated by Django 5.1.5 on 2026-04-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_add_under_order_country_of_origin_fix_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireLoadIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='Значение')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Индекс нагрузки',
                'verbose_name_plural': 'Индексы нагрузки',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='TireSpeedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5, unique=True, verbose_name='Значение')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Индекс скорости',
                'verbose_name_plural': 'Индексы скорости',
                'ordering': ['value'],
            },
        ),
        migrations.AlterField(
            model_name='tireproduct',
            name='load_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.tireloadindex', verbose_name='Индекс нагрузки'),
        ),
        migrations.AlterField(
            model_name='tireproduct',
            name='speed_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.tirespeedindex', verbose_name='Индекс скорости'),
        ),
    ]
