# Generated by Django 5.0.7 on 2026-05-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_add_seller_website_url'),
        ('shop', '0010_carousel_slide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('privacy', 'Политика конфиденциальности'), ('personal_data', 'Обработка персональных данных'), ('offer', 'Публичная оферта'), ('buyer_rules', 'Правила покупки'), ('seller_rules', 'Правила продажи'), ('tech_recommendations', 'Рекомендуемые технологии'), ('terms', 'Пользовательское соглашение'), ('return_policy', 'Условия возврата')], max_length=30, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Документ сайта',
                'verbose_name_plural': 'Документы сайта',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='LINKAVTO', max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон')),
                ('phone_display', models.CharField(blank=True, default='', help_text='Например: +7 (999) 999-99-99', max_length=30, verbose_name='Телефон (отображение)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='CategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание / обоснование')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_request', to='shop.category', verbose_name='Созданная категория')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Укажите, в какую категорию должна войти новая подкатегория', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='shop.category', verbose_name='Родительская категория')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_category_requests', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_requests', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Заявка на категорию',
                'verbose_name_plural': 'Заявки на категории',
                'ordering': ['-created_at'],
            },
        ),
    ]
