# Generated by Django 5.0.7 on 2026-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_initial'),
    ]

    # This migration was introduced in parallel with 0013_initial and duplicated
    # the same schema changes. Keep it as a no-op after 0013_initial so existing
    # databases do not fail with DuplicateColumn during deploy.
    operations = []
