# Generated by Django 5.0.7 on 2026-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_add_category_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedocument',
            name='file',
            field=models.FileField(blank=True, help_text='PDF, DOC и т.д. Если загружен файл — на странице появится кнопка скачивания', null=True, upload_to='documents/', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='sitedocument',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Содержание'),
        ),
    ]
