# Generated by Django 5.0.7 on 2026-05-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_initial'),
        ('shop', '0013_sitedocument_add_file'),
    ]

    operations = []
