# Generated by Django - Initial migration for garage app with GenericForeignKey

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('generation_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('modification_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(help_text='Например: "Моя машина", "Рабочий грузовик"', max_length=200, verbose_name='Пользовательское название')),
                ('vin', models.CharField(blank=True, help_text='17-значный VIN номер', max_length=17, null=True, verbose_name='VIN номер')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='garage/vehicles/%Y/%m/', verbose_name='Пользовательское фото')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если транспорт используется', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['carbrand', 'truckbrand', 'motobrand', 'specialbrand']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_brand_vehicles', to='contenttypes.contenttype')),
                ('generation_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['cargeneration', 'truckgeneration', 'motogeneration', 'specialgeneration']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_generation_vehicles', to='contenttypes.contenttype')),
                ('model_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['carmodel', 'truckmodel', 'motomodel', 'specialmodel']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_model_vehicles', to='contenttypes.contenttype')),
                ('modification_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['carmodification', 'truckmodification', 'motomodification', 'specialmodification']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_modification_vehicles', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательское транспортное средство',
                'verbose_name_plural': 'Пользовательские транспортные средства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='garage.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', 'is_active'], name='garage_vehi_user_id_5c9f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='garage_vehi_vin_3d3a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='garage_vehi_license_6c44b7_idx'),
        ),
    ]
