# Generated by Django 5.1.5 on 2026-02-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='garage_vehi_user_id_0cdf96_idx',
            old_name='garage_vehi_user_id_5c9f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='garage_vehi_vin_357727_idx',
            old_name='garage_vehi_vin_3d3a5e_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='garage_vehi_license_32aced_idx',
            old_name='garage_vehi_license_6c44b7_idx',
        ),
    ]
